name: Learning GitHub Script
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |
          github.rest.issues.get({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
